#! /bin/sh

echo "mount all file system..."
mkdir /dev/pts
/bin/mount -av

runlevel=S
prevlevel=N
umask 022
export runlevel prevlevel

mkdir /var/cache
mkdir /var/run
mkdir /var/log
mkdir /var/spool

echo "**************************"
echo "    Love Linux ! ! ! "
echo "**************************"

/bin/hostname -F /etc/sysconfig/HOSTNAME

#local service
/etc/init.d/rc.local
